import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { keypairFromSeed32, signEd25519 } from '../src/crypto/ed25519.js';
import { bytesToHex } from '../src/crypto/hash.js';
import { quorumThreshold, verifyFinalityProof, voteSigningMessage } from '../src/proofs/finality.js';

// Generated by core (tests/test_finality_certificate.cpp, test_finality_shared_vectors_match_ts),
// which fails if core's vote signing no longer produces this file byte for byte.
interface FinalityVectorCase {
  name: string;
  height: string;
  round: number;
  transition_hash: string;
  message_hex: string;
  signatures: { pubkey_hex: string; sig_hex: string }[];
  expected: boolean;
}

const vectors = JSON.parse(
  readFileSync(resolve(process.cwd(), 'test-vectors/finality_vectors.json'), 'utf8'),
) as { committee: string[]; cases: FinalityVectorCase[] };

function seed(n: number): Uint8Array {
  const s = new Uint8Array(32);
  for (let i = 0; i < s.length; i++) s[i] = (n * 17 + i) & 0xff;
  return s;
}

describe('finality proof verification', () => {
  it('computes quorum threshold as floor(2N/3)+1', () => {
    expect(quorumThreshold(1)).toBe(1);
    expect(quorumThreshold(2)).toBe(2);
    expect(quorumThreshold(3)).toBe(3);
    expect(quorumThreshold(4)).toBe(3);
    expect(quorumThreshold(10)).toBe(7);
  });

  it('has core-generated vectors', () => {
    expect(vectors.committee.length).toBe(4);
    expect(vectors.cases.length).toBeGreaterThan(0);
  });

  for (const c of vectors.cases) {
    it(`reconstructs core's signed message: ${c.name}`, () => {
      expect(bytesToHex(voteSigningMessage(BigInt(c.height), c.round, c.transition_hash))).toBe(c.message_hex);
    });

    it(`matches core's verdict: ${c.name}`, () => {
      const cert = { height: BigInt(c.height), round: c.round, transition_hash: c.transition_hash, signatures: c.signatures };
      expect(verifyFinalityProof(cert, vectors.committee)).toBe(c.expected);
    });
  }

  it('round-trips signatures made over voteSigningMessage', () => {
    const kps = [1, 2, 3, 4].map((n) => keypairFromSeed32(seed(n)));
    const committee = kps.map((k) => k.pubkeyHex);
    const transition = 'ab'.repeat(32);
    const msg = voteSigningMessage(77, 1, transition);
    const signatures = kps.slice(0, 3).map((k) => ({ pubkey_hex: k.pubkeyHex, sig_hex: bytesToHex(signEd25519(msg, k.privkeyHex)) }));
    expect(verifyFinalityProof({ height: 77, round: 1, transition_hash: transition, signatures }, committee)).toBe(true);
    expect(verifyFinalityProof({ height: 77, round: 2, transition_hash: transition, signatures }, committee)).toBe(false);
  });

  it('fails closed on malformed input', () => {
    const committee = vectors.committee;
    const base = vectors.cases.find((c) => c.name === 'quorum_3_of_4')!;
    const sigs = base.signatures;
    expect(verifyFinalityProof({ height: 1, round: 0, transition_hash: 'zz', signatures: sigs }, committee)).toBe(false);
    expect(verifyFinalityProof({ height: 1, round: -1, transition_hash: base.transition_hash, signatures: sigs }, committee)).toBe(false);
    expect(
      verifyFinalityProof(
        { height: BigInt(base.height), round: base.round, transition_hash: base.transition_hash, signatures: [{ pubkey_hex: committee[0], sig_hex: 'not-hex' }] },
        committee,
      ),
    ).toBe(false);
    expect(verifyFinalityProof({ height: BigInt(base.height), round: base.round, transition_hash: base.transition_hash, signatures: sigs }, [])).toBe(false);
  });
});
