#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Boot the 3-node Docker devnet from the newest generate_fresh_genesis.sh output.
#
# 1. Load devnet/<newest>/manifest.env.
# 2. `docker-compose down -v` to purge old containers and data volumes.
# 3. Write devnet/<stamp>/docker-compose.devnet.yml, which overlays the shared
#    services in docker-compose.yml: bind-mounts that devnet's genesis.bin and
#    per-node keystore (read-only), and passes the passphrase via environment.
#    Passphrases go to devnet/<stamp>/.env (0600), read with --env-file, so later
#    `docker-compose ... logs/down` calls work from a fresh shell.
# 4. `docker-compose up -d --build`; every node starts from height 0.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_COMPOSE="$ROOT_DIR/docker-compose.yml"
NODES=(node1 node2 node3)
P2P_PORT=19440

DEVNET_DIR=""
BUILD=1

usage() {
  cat <<EOF
usage: $(basename "$0") [options]

  --dir DIR     use this devnet folder instead of the newest under devnet/
  --no-build    do not rebuild the node image
  -h, --help    show this help
EOF
}

die() { echo "error: $*" >&2; exit 1; }
log() { echo "[devnet] $*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir)      DEVNET_DIR="${2:?--dir requires a value}"; shift 2 ;;
    --no-build) BUILD=0; shift ;;
    -h|--help)  usage; exit 0 ;;
    *)          usage >&2; die "unknown argument: $1" ;;
  esac
done

command -v docker-compose >/dev/null || die "docker-compose (v1) is not installed"
COMPOSE=(docker-compose)

# --- locate manifest ----------------------------------------------------------
if [[ -z "$DEVNET_DIR" ]]; then
  # Folder names are UTC timestamps, so lexical order is chronological.
  DEVNET_DIR="$(find "$ROOT_DIR/devnet" -mindepth 2 -maxdepth 2 -name manifest.env -printf '%h\n' 2>/dev/null \
    | sort | tail -n1)"
  [[ -n "$DEVNET_DIR" ]] || die "no devnet/*/manifest.env found; run scripts/generate_fresh_genesis.sh first"
fi
DEVNET_DIR="$(cd "$DEVNET_DIR" && pwd)"
MANIFEST="$DEVNET_DIR/manifest.env"
[[ -f "$MANIFEST" ]] || die "missing $MANIFEST"

# shellcheck source=/dev/null
source "$MANIFEST"

[[ "${VALIDATOR_COUNT:-}" == "${#NODES[@]}" ]] \
  || die "manifest has VALIDATOR_COUNT=${VALIDATOR_COUNT:-?}; docker-compose.yml defines ${#NODES[@]} nodes"
[[ -f "$DEVNET_DIR/$GENESIS_BIN" ]] || die "missing $DEVNET_DIR/$GENESIS_BIN"

log "using $DEVNET_DIR"
log "profile=$DEVNET_PROFILE genesis_hash=$GENESIS_HASH"
if [[ "$DEVNET_PROFILE" == "production" ]]; then
  log "warning: booting production-profile keys on a local devnet"
fi

# --- passphrases (written to .env, never to the override file) ----------------
ENV_FILE="$DEVNET_DIR/.env"
env_lines=()
for ((i = 1; i <= VALIDATOR_COUNT; i++)); do
  key_var="VALIDATOR_${i}_KEY"
  [[ -f "$DEVNET_DIR/${!key_var}" ]] || die "missing $DEVNET_DIR/${!key_var}"

  pass_file_var="VALIDATOR_${i}_PASS_FILE"
  pass_var="VALIDATOR_${i}_PASSPHRASE"
  if [[ -n "${!pass_file_var:-}" ]]; then
    [[ -f "$DEVNET_DIR/${!pass_file_var}" ]] || die "missing $DEVNET_DIR/${!pass_file_var}"
    pass="$(<"$DEVNET_DIR/${!pass_file_var}")"
  else
    pass="${!pass_var:-}"
  fi
  [[ -n "$pass" ]] || die "no passphrase for validator $i"
  env_lines+=("FINALIS_DEVNET_PASS_$i=$pass")
done
( umask 077; printf '%s\n' "${env_lines[@]}" > "$ENV_FILE" )
chmod 600 "$ENV_FILE"

# --- compose override ---------------------------------------------------------
OVERRIDE="$DEVNET_DIR/docker-compose.devnet.yml"
{
  echo "# Generated by scripts/devnet_up.sh for devnet $DEVNET_CREATED_UTC -- do not edit"
  echo "# genesis_hash=$GENESIS_HASH"
  echo "services:"
  for ((i = 1; i <= VALIDATOR_COUNT; i++)); do
    node="${NODES[i - 1]}"
    key_var="VALIDATOR_${i}_KEY"
    peers=()
    for other in "${NODES[@]}"; do
      [[ "$other" == "$node" ]] || peers+=("$other:$P2P_PORT")
    done
    peer_list="$(IFS=,; echo "${peers[*]}")"

    # --with-lightserver is omitted: the runtime image has no
    # finalis-lightserver binary. --seeds keeps Node::init from appending the
    # public mainnet default seeds.
    cat <<EOF
  $node:
    environment:
      FINALIS_VALIDATOR_PASSPHRASE: "\${FINALIS_DEVNET_PASS_$i:?}"
    volumes:
      - "$DEVNET_DIR/$GENESIS_BIN:/opt/finalis-core/devnet/genesis.bin:ro"
      - "$DEVNET_DIR/${!key_var}:/opt/finalis-core/devnet/validator.json:ro"
    command:
      - "--db"
      - "/var/lib/finalis/db"
      - "--genesis"
      - "/opt/finalis-core/devnet/genesis.bin"
      - "--allow-unsafe-genesis-override"
      - "--node-id"
      - "$i"
      - "--validator-key-file"
      - "/opt/finalis-core/devnet/validator.json"
      - "--validator-passphrase-env"
      - "FINALIS_VALIDATOR_PASSPHRASE"
      - "--listen"
      - "--bind"
      - "0.0.0.0"
      - "--port"
      - "$P2P_PORT"
      - "--no-dns-seeds"
      - "--peers"
      - "$peer_list"
      - "--seeds"
      - "$peer_list"
EOF
  done
} > "$OVERRIDE"

COMPOSE+=(-f "$BASE_COMPOSE" -f "$OVERRIDE" --env-file "$ENV_FILE")

# --- purge old state and boot -------------------------------------------------
log "stopping old devnet and removing data volumes"
"${COMPOSE[@]}" down -v --remove-orphans

up_args=(up -d)
[[ "$BUILD" == 1 ]] && up_args+=(--build)
log "starting ${NODES[*]}"
"${COMPOSE[@]}" "${up_args[@]}" "${NODES[@]}"

"${COMPOSE[@]}" ps
log "logs: docker-compose -f docker-compose.yml -f ${DEVNET_DIR#"$ROOT_DIR"/}/docker-compose.devnet.yml --env-file ${DEVNET_DIR#"$ROOT_DIR"/}/.env logs -f"
